package com.taotao.mapper;

import com.taotao.bean.ItemParam;
import com.taotao.bean.ItemParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ItemParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    int countByExample(ItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    int deleteByExample(ItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    int insert(ItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    int insertSelective(ItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    List<ItemParam> selectByExampleWithBLOBs(ItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    List<ItemParam> selectByExample(ItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    ItemParam selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    int updateByExampleSelective(@Param("record") ItemParam record, @Param("example") ItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    int updateByExampleWithBLOBs(@Param("record") ItemParam record, @Param("example") ItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    int updateByExample(@Param("record") ItemParam record, @Param("example") ItemParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    int updateByPrimaryKeySelective(ItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    int updateByPrimaryKeyWithBLOBs(ItemParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_item_param
     *
     * @mbggenerated Fri Apr 03 22:25:03 CST 2020
     */
    int updateByPrimaryKey(ItemParam record);
}